import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LandingLayout from "../components/layout/Layout";
import { Box, Text } from "@chakra-ui/react";
import Hero from "../components/sections/Hero";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Starr Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingLayout>
        <Box minH="100vh">
          <Hero />
        </Box>
      </LandingLayout>
    </div>
  );
}
